name: tooltip_plus
description: "A Flutter tooltip widget that offers rich customization and smart positioning to enhance user experience."
version: 0.0.1
homepage: https://github.com/NamTranDinh/tooltip_plus
documentation: https://github.com/NamTranDinh/tooltip_plus/blob/main/README.md
repository: https://github.com/NamTranDinh/tooltip_plus
issue_tracker: https://github.com/NamTranDinh/tooltip_plus/issues
topics:
  - tooltip
  - tooltip-widget
  - custom-tooltip
keywords:
  - tooltip
  - tooltip-widget
  - custom-tooltip

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
